import os
import pandas as pd
import snowflake.connector

# Read CSV generated by fetch_weather.py
df = pd.read_csv("/Users/rakshandahedaoo/Desktop/daily-weather-etl/weather_output.csv")

# Establish Snowflake connection
conn = snowflake.connector.connect(
    user=os.getenv("SNOWFLAKE_USER"),
    password=os.getenv("SNOWFLAKE_PASSWORD"),
    account=os.getenv("SNOWFLAKE_ACCOUNT"),
    warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
    database=os.getenv("SNOWFLAKE_DATABASE"),
    schema=os.getenv("SNOWFLAKE_SCHEMA")
)

cs = conn.cursor()
try:
    # Create table if not exists
    cs.execute("""
        CREATE TABLE IF NOT EXISTS weather_raw (
            city STRING,
            temperature FLOAT,
            humidity FLOAT,
            weather STRING,
            timestamp TIMESTAMP
        )
    """)

    # Insert data row-by-row
    for _, row in df.iterrows():
        cs.execute(
            """
            INSERT INTO weather_raw (city, temperature, humidity, weather, timestamp)
            VALUES (%s, %s, %s, %s, %s)
            """,
            (row.city, row.temperature, row.humidity, row.weather, row.timestamp)
        )
finally:
    cs.close()
    conn.close()
    print("✅ Data successfully loaded into Snowflake!")
